[package]
name = "bevyjam"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.10"
bevy-inspector-egui = "0.18"
bevy_asset_loader = "0.16"
rand = "0.8"
webbrowser = "0.8"
