[package]
name = "suborbital"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "532f3cb" }
rand = "0.8"
webbrowser = "0.8"
